# file: docker-compose.yml
# Modul 141  
#
# Container mit PSQL und pgAdmin4
# Version für Linux
# 
# Dominik Reuss
#
###################################

services:
  db:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: password
    networks:
      - pgnetwork
    ports:
      - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data/:rw

  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - pgnetwork
    ports:
      - "8081:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin/:rw

networks:
  pgnetwork: 
    driver: bridge
  
volumes:
  pgadmin-data:
  postgres-data:
 


